# Generated by Django 4.1.9 on 2023-10-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
