# Generated by Django 4.1.9 on 2023-10-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0003_sala_asiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asiento',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
