# Generated by Django 4.0.5 on 2023-11-18 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0005_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=90, null=True)),
                ('monto_producto', models.IntegerField(blank=True, default=1, null=True)),
                ('precio_producto', models.IntegerField()),
                ('fecha_factura', models.DateTimeField(auto_now=True)),
                ('estado_factura', models.CharField(blank=True, default='Pendiente', max_length=40, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas.perfilusuario')),
            ],
        ),
    ]
