# Generated by Django 4.0.5 on 2023-11-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0006_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(blank=True, default='Sin Rut', max_length=40, null=True),
        ),
    ]
