# Generated by Django 3.2.4 on 2023-12-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0007_perfilusuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
